name: Schedule

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "lts/*"
      - name: Build types
        run: |
          make
          make build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: scheduled build types"
